### PR TITLE
Allow multiple emoticons to map to an emoji.

### PR DESCRIPTION
**Pull request by xiaohenry**
- Allow multiple emoticons to map to an emoji.
- A few other small fixes, such as removing spaces from emoticons and typos

### CODE REVIEW

**Comment by xiaohenry** [comment]
I associated this Github account with Google. Can you try re-running the check?

**Comment by rsheeter** [comment]
> I associated this Github account with Google

Arrived just as I was typing you probably need to do that!

**Comment by rsheeter** [comment]
image

**Comment by rsheeter** [comment]
OK, now it's happy. Must just be a delay somewhere.

**Review by rsheeter — APPROVED** [review]

**Pull request merged**
